[project]
name = "ruitl-example"
version = "0.1.0"
description = "Example RUITL project configuration"
authors = ["RUITL Team"]

[build]
template_dir = "templates"
out_dir = "generated"
src_dir = "src"
